global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'milvus'
    static_configs:
      - targets: ['standalone:9091']

  - job_name: 'mcp'
    static_configs:
      - targets: ['mcp:8000']